name: CI
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - run: sbt -v +test
